version: "3.9"
services:
  app:
    build: .
    container_name: medical-chatbot-app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - ollama
    volumes:
      - ./medical_cs:/app/medical_cs
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medical_cs
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/medical_cs_db.sql:/docker-entrypoint-initdb.d/init.sql

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./Modelfile:/Modelfile
      - ./model_pull.sh:/model_pull.sh
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "ollama serve & sleep 5 && sh /model_pull.sh && tail -f /dev/null",
      ]

volumes:
  mysql_data:
  ollama_data:
